[versions]
guava = "33.2.1-jre"
junit-jupiter = "5.10.3"
kafka = "3.7.1"
responsive = "0.32.0"
slf4j = "2.0.5"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kafka = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
responsive = { module = "dev.responsive:kafka-client", version.ref = "responsive" }
logging = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
